### ISSUE TITLE
No such file or directory (os error 2)

### ISSUE THREAD

**Issue by paulyoung** [dfinity/cdk-rs#100]
I followed [Hello, World! Rust CDK Quick Start](https://sdk.dfinity.org/docs/rust-guide/rust-quickstart.html) and ran into some trouble at the `dfx deploy` step. I'm using `dfx` version `0.7.0-beta.8`.

```
$ dfx deploy
Deploying all canisters.
All canisters have already been created.
Building canisters...
Executing 'cargo build --target wasm32-unknown-unknown --package rust_hello --release'
    Finished release [optimized] target(s) in 0.15s
The post-build step failed for canister 'rrkah-fqaaa-aaaaa-aaaaq-cai' with an embedded error: No such file or directory (os error 2)
```

**Comment by paulyoung** [comment]
Fixed the title, copy and paste error.

**Comment by paulyoung** [comment]
The issue appears to be with the instruction to create `src/rust_hello/src/rust_hello.did` but to use this in `dfx.json`:

```
"candid": "src/rust_hello/rust_hello.did",
```

I'll make a PR to update the docs, assuming that `src/rust_hello/src/rust_hello.did` is the correct path.

**Comment by paulyoung** [comment]
Looks like some of the CI checks are failing with `Error: Resource not accessible by integration`

@hansl, would you mind taking a look?

**Comment by lsgunnlsgunn** [comment]
I think the path to the Candid file has been fixed in a different ticket.
