### ISSUE TITLE
Nothing was printed after I called "dfx canister call rust_hello print"

### ISSUE THREAD

**Issue by uney** [dfinity/cdk-rs#106]
It shows () only without the content

**Comment by lsgunnlsgunn** [comment]
Do you remember whether you ran `dfx start` or `dfx start --background`?
If you used `dfx start`, the output is sent to the terminal where network log messages are displayed instead of the terminal where you run the `dfx canister call` command.

**Comment by uney** [comment]
I tried both

**Comment by cnrmck** [comment]
@uney a copy of the logs from the failure would probably help. What do you see when you run `dfx start`? What about when you open a new terminal and run `dfx canister call rust_hello print`? 

Also, could you share the contents of your `dfx.json` and `./src/rust_hello/src/rust_hello.did` and `./src/rust_hello/src/lib.rs` files?

**Comment by cnrmck** [comment]
I have also run into this bug just recently. I haven't been able to replicate it. 

I fixed it by running `dfx stop && dfx start --clean --background && dfx deploy`

**Comment by NITHISH862002** [comment]
It worked for me.

**Comment by PythonForEverthing** [comment]
Save the code and deploy it again
