### ISSUE TITLE
thread '<unnamed>' panicked at 'debug_print should only be called inside canisters.

### ISSUE THREAD

**Issue by aymanfmustafa** [dfinity/cdk-rs#107]
I would like to build an app on IC with an iOS frontend. When attempting to call the Hello World sample from the iOS frontend, I got this error:

thread '<unnamed>' panicked at 'debug_print should only be called inside canisters.', /Users/Ayman/.cargo/registry/src/github.com-1ecc6299db9ec823/ic-cdk-0.3.0/src/api/ic0.rs:60:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
libc++abi: terminating with uncaught foreign exception

The canister was deployed to the local replica. Any suggestions? Thanks.

**Comment by adamspofford-dfinity** [comment]
Is your iOS app using the ic-cdk crate? ic-cdk should be used by canisters; interfacing with canisters from outside the IC is done via the ic-agent crate.
