### ISSUE TITLE
any limitation in using rust to develop ic?

### ISSUE THREAD

**Issue by aihuawu** [dfinity/cdk-rs#123]
I believe the advantage of rust over motoko is there are a lot of rust packages available.
Can I use all the packages for rust? can I compile all rust to target web assembly?
Any limitation in using rust?

George Wu

**Comment by adamspofford-dfinity** [comment]
Rust is a great language to develop on the IC, and many of our official canisters like certified-assets and cycles-wallet are written in Rust. The limitations are those of any other WebAssembly target; `std` is available, but most functions available in `std` but not in `alloc` other than threading primitives will panic/error/generally do nothing useful, such as `std::fs` functions. This should allow you to compile against most any crate, but any code path that actually *attempts* to, for example, read the file-system, will unconditionally error. Shouldn't be a problem for any library crates that don't interact with I/O at all.
