### ISSUE TITLE
attempting to run chess on macbook m1

### ISSUE THREAD

**Issue by gschian0** [dfinity/cdk-rs#135]
**I run to start the rust chess example**

`dfx start --background --clean`
`dfx deploy`

**and get this error**

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/gennaroschiano/.nvm/versions/node/v14.17.6/bin/node',
1 verbose cli   '/Users/gennaroschiano/.nvm/versions/node/v14.17.6/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle new_project@0.1.0~prebuild: new_project@0.1.0
6 info lifecycle new_project@0.1.0~build: new_project@0.1.0
7 verbose lifecycle new_project@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle new_project@0.1.0~build: PATH: /Users/gennaroschiano/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/gennaroschiano/Documents/GitHub/cdk-rs/examples/chess/node_modules/.bin:/Users/gennaroschiano/.opam/default/bin:/Users/gennaroschiano/Documents/Tezos/newtry/tezos/docs/ligo:/Users/gennaroschiano/.nvm/versions/node/v14.17.6/bin:/opt/homebrew/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/gennaroschiano/.nix-profile/bin:/Users/gennaroschiano/.cargo/bin
9 verbose lifecycle new_project@0.1.0~build: CWD: /Users/gennaroschiano/Documents/GitHub/cdk-rs/examples/chess
10 silly lifecycle new_project@0.1.0~build: Args: [ '-c', 'webpack' ]
11 silly lifecycle new_project@0.1.0~build: Returned: code: 2  signal: null
12 info lifecycle new_project@0.1.0~build: Failed to exec build script
13 verbose stack Error: new_project@0.1.0 build: `webpack`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/gennaroschiano/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/Users/gennaroschiano/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid new_project@0.1.0
15 verbose cwd /Users/gennaroschiano/Documents/GitHub/cdk-rs/examples/chess
16 verbose Darwin 20.6.0
17 verbose argv "/Users/gennaroschiano/.nvm/versions/node/v14.17.6/bin/node" "/Users/gennaroschiano/.nvm/versions/node/v14.17.6/bin/npm" "run" "build"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 2
22 error new_project@0.1.0 build: `webpack`
22 error Exit status 2
23 error Failed at the new_project@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]`

**Comment by lwshang** [comment]
Hi @gschian0!
We recently overhauled all examples in #149 and #151. The chess example especially got update frontend in #152. Would you like to try again the example in your environment to see if the problem has been fixed?

**Comment by smallstepman** [comment]
Since there hasn't been any activity on this issue for a year, I'm going to close it. If you're still experiencing this problem, please feel free to reopen it.

Thanks!
