### ISSUE TITLE
Import macro generate code where error can't be catched when calling a canister which traps

### ISSUE THREAD

**Issue by shalexbas** [dfinity/cdk-rs#157]
When importing a candid file with the import macro then the generated code should looks like this (ic-cdk-macros-0.3.2\src\import.rs):
```
...
Ok(format!(
            r#"
            {{
                {call}(
                  ic_cdk::export::Principal::from_text("{principal}").unwrap() as ic_cdk::export::Principal,
                  "{name}",
                  {arguments}
                 )
                 .await
                 .unwrap()
            }}
        "#,
...
```
Here unwrap is called directly, so if the called canister traps then the calling canister traps as well. 
Maybe the generated code shouldn't call unwrap() and the developer can decide what to do if the calling canister traps.

I already tried **catch_unwind()** (futures::FutureExt) but the caller canister still traps.

See https://forum.dfinity.org/t/rust-cdk-how-to-catch-panic-trap-when-calling-another-canister-which-traps/7886/

**Comment by vihanb** [comment]
+1 on this. I find cross-canister error handling very important, but I understand the pitfalls in implementing this in a backwards compatible way. Some option for this seems like a critical features though.

**Comment by chenyan-dfinity** [comment]
The latest `didc` can generate Rust binding from did file: `didc bind a.did -t rs`, which doesn't use `unwrap`. You can put the generated file as part of your codebase as a stop-gap measure.

You can download the tool at https://github.com/dfinity/candid/releases/tag/2021-12-20
