### ISSUE TITLE
CDK should support newly added `controller_size` and `controller_copy`

### ISSUE THREAD

**Issue by enzoh** [dfinity/cdk-rs#16]

**Comment by hansl** [comment]
These are not in the public spec yet (they're internal APIs likely to change), so I'll mark this as blocked.

**Comment by levifeldman** [comment]
This is a helpfull feature, can a canister see the list of its own controllers? many canisters will want to limit some methods for their controllers.

**Comment by nomeata** [comment]
> many canisters will want to limit some methods for their controllers.

The recommendation is to _not_ conflate canister controller with application level roles, and implement your authentication logic in the canister as you see fit, for example using an admin list. You can initialize it with the controller upon installation.

Or would you expect that on a LAMP system, the system's `root` user can log into the web application running on it?

**Comment by levifeldman** [comment]
That may be for the old model of the web, where users never own their data. I want my users to controll their own canisters, so that they controll and own their own data in the truest way. The controllers are the admins and the admins are the controllers.

**Comment by levifeldman** [comment]
Oh I can call the management canister canister_status
