### ISSUE TITLE
Cannot call on inspect_message

### ISSUE THREAD

**Issue by 0x000000000000000** [dfinity/cdk-rs#165]
#[inspect_message]
async fn inspect_message() {
    ic_cdk::api::call::accept_message();
    let event_canister_id =  Principal::from_text("rkp4c-7iaaa-aaaaa-aaaca-cai").unwrap();
    let result:CallResult<()> = ic_cdk::api::call::call(event_canister_id,"createEvent",()).await;
}
I tried to call in the inspect_message, but failed, but it works normally in the function of update type. This is an error returned. Does anyone know how to solve it.

The replica returned an HTTP Error: Http Error: status 500 Internal Server Error, content type "", content: Requested canister failed to process the message acceptance request

**Comment by nomeata** [comment]
You cannot do inter canister calls from `inspect_message`, this is simply not possible on the IC.

**Comment by 0x000000000000000** [comment]
thanks
