### ISSUE TITLE
Management canister not found

### ISSUE THREAD

**Issue by lastmjs** [dfinity/cdk-rs#173]
Forum post: https://forum.dfinity.org/t/management-canister-not-found/9049

I am using dfx v0.8.4. I am trying to do a cross-canister call to the management canister like I've done before:

```rust
let call_result: Result<(Vec<u8>,), _> = ic_cdk::api::call::call(
    ic_cdk::export::Principal::management_canister(),
    // ic_cdk::export::Principal::from_text("aaaaa-aa").unwrap(),
    "raw_rand",
    ()
).await;
```

Each way of calling the management canister above (one is commented out) results in the following error:

```bash
[Canister rrkah-fqaaa-aaaaa-aaaaq-cai] Panicked at 'called `Result::unwrap()` on an `Err` value: (DestinationInvalid, "Canister o5alr-fkgwv-ukoa3-em3wh-7cj4t-ngizi-krl3c-v44po-ar5jg-a5agw-pqe not found")', canisters/call/src/lib.rs:125:44
```

**Comment by roman-kashitsyn** [comment]
Hi @lastmjs! 
Do you call the management canister from a query method?

Cross-canister calls from a query aren't properly supported at the moment. In particular, management canister calls produce error messages similar to the one you posted.

Furthermore, there is no way to get secure unpredictable randomness in a query call. So even if inter-canister query calls were supported, I doubt that "raw_rand" would work.

I'm closing this issue, for now. Please reopen it if you get this error in an update method.

**Comment by ildefons** [comment]
I changed to 'update' but I get the same error (below)

   Compiling rust_hello v0.1.0 (/home/ildefons/rstest/rust_hello/src/rust_hello)
error[E0433]: failed to resolve: could not find `CanisterId` in `ic_cdk`
  --> src/rust_hello/src/lib.rs:55:39
   |
55 |     let management_canister = ic_cdk::CanisterId::from(Vec::new());
   |                                       ^^^^^^^^^^ could not find `CanisterId` in `ic_cdk`
