### ISSUE TITLE
`ic-certified-map` release `0.2.0` not documented in the `CHANGELOG.md`

### ISSUE THREAD

**Issue by ggreif** [dfinity/cdk-rs#176]
See: https://github.com/dfinity/cdk-rs/blob/main/src/ic-certified-map/CHANGELOG.md

But it is certainly out in the wild: https://docs.rs/ic-certified-map/0.2.0/ic_certified_map

The `[Unreleased]` section is touched by https://github.com/dfinity/cdk-rs/commit/2112e912e156b271389a51777680de542bb43980, which is post-`0.2.0`.

As a side-request, can we have a new release from `main`? [dfinity/ic](https://github.com/dfinity/ic) won't build with "0.2.0" as some trait derivations are missing.

**Comment by frederikrothenberger** [comment]
[dfinity/internet-identity](https://github.com/dfinity/internet-identity/) also requires a newer release than "0.2.0".

**Comment by nmattia** [comment]
@eric-swanson @roman-kashitsyn can you cut a release or get in touch with the relevant people? Thanks!
