### ISSUE TITLE
One-way calls

### ISSUE THREAD

**Issue by paulyoung** [dfinity/cdk-rs#188]
@nomeata, in your post on [Zero-downtime upgrades of Internet Computer canisters](https://www.joachim-breitner.de/blog/789-Zero-downtime_upgrades_of_Internet_Computer_canisters), you said:

> On Rust, you have to use the System API directly or wait for `cdk-rs` to provide this ability (patches welcome, happy to advise)

Please can you advise? 🙂

**Comment by nomeata** [comment]
Well, provide a variant of the call functions that passes `-1` for the `reply_fun` and `reject_fun` argument to `ic0.call_new`, and of course no handling/decoding of responses

**Comment by aewc** [comment]
What range is the real function pointer address of `reply_fun` and `reject_fun`? At this point I discovered the benefit of setting the pointer type to i32 instead of u32. Magic, emmm

**Comment by nomeata** [comment]
It’s not really a function pointer address, but it’s a WebAssembly table entry index, and these start at 0 and (so far at least) are consecutive. So 0xffffffff is a pretty good guess at an invalid one.
