### ISSUE TITLE
ic_cdk::notify not works

### ISSUE THREAD

**Issue by witter-deland** [dfinity/cdk-rs#265]
## I tried using ic_cdk::notify but it doesn't work.
**environment**:
dfx 0.10.0
nodejs v16.13.2
cargo 1.61.0

ic-cdk = "0.5.1"
ic-cdk-macros = "0.5.1"

### How do I use it?
- receiver(onTokenReceived): https://github.com/witter-deland/fungible-token-standard/blob/notify/src/dft_receiver/src/receiver.rs
- caller: https://github.com/witter-deland/fungible-token-standard/blob/8e5c78ffa58c16207a64e1ad590d9fd309df7630/src/dft_basic/src/canister_api/transfer_notify.rs#L23
### Expected result
The BDD test here should pass, **but** it doesn't: https://github.com/witter-deland/fungible-token-standard/blob/8e5c78ffa58c16207a64e1ad590d9fd309df7630/src/scripts/features/receiverNotify.feature#L17

### How to reproduce the issue?
```
git clone https://github.com/witter-deland/fungible-token-standard
cd fungible-token-standard/src
git checkout notify
dfx start --clean
sh sh_setup_dev.sh
sh it_dev.sh 
```

### More detailed issue description

1. you can see the log in dfx console, it means that ic_cdk::notify is called:
```
[Canister ryjl3-tyaaa-aaaaa-aaaba-cai] DEBUG - TransferNotifyAPI::notify in
[Canister ryjl3-tyaaa-aaaaa-aaaba-cai] INFO - TransferNotifyAPI::notify:  will notify receiver: "qoctq-giaaa-aaaaa-aaaea-cai",transfer_from is 7de29df379f23dfdebb2b7ae6f1af883b9985b7808631d5446295991f0138f9c,transfer_value is 100000000000000000000
```

2.  query method notificationCount  should return 1 ,but return 0 now: https://github.com/witter-deland/fungible-token-standard/blob/8e5c78ffa58c16207a64e1ad590d9fd309df7630/src/dft_receiver/src/receiver.rs#L45

### BUT
1. when I try dfx command :
```shell
dfx canister call dft_receiver onTokenReceived '("7de29df379f23dfdebb2b7ae6f1af883b9985b7808631d5446295991f0138f9c",1000:nat)'

```

you will see log in dfx console :

```[Canister qoctq-giaaa-aaaaa-aaaea-cai] DEBUG - on_token_received in    
[Canister qoctq-giaaa-aaaaa-aaaea-cai] DEBUG - DFT is "7b6mv-nyoey-gkj2b-2r6mp-fa2rr-6ktwc-qrx7e-l3eax-32jd7-ahwnj-3qe",from is "7de29df379f23dfdebb2b7ae6f1af883b9985b7808631d5446295991f0138f9c",value is 1_000
```

2. and check the notificationCount is (1 : nat64):
```shell
dfx canister call dft_receiver notificationCount
```

Please help to check if I am using notify incorrectly? If not, is this a CDK bug?

**Comment by domwoe** [comment]
Hey @witter-deland,

That's strange. I don't see what's wrong here. 

To try the new notify API myself, I changed the [pub/sub example](https://github.com/dfinity/examples/tree/master/rust/pub-sub) to use the notify API and it works (see [here](https://github.com/domwoe/examples/blob/fd806e55736dad3fe26cabb2fa8a0222579537b7/rust/pub-sub/src/publisher/src/lib.rs#L41)).

**Comment by witter-deland** [comment]
Thank you very much for your kind reply @domwoe .
I'm also wondering why my call to this doesn't work. I believe that the cdk developers have been well tested before release, I am confused, so I came to ask for help, hoping to get help from the cdk developers

**Comment by BrantBrown** [comment]
I‘ve find out the reason
                    ((transfer_from.clone(), nat_transfer_value),),
    should be
                    (transfer_from.clone(), nat_transfer_value,),

**Comment by witter-deland** [comment]
It works. But unwrap not works is a issue at here https://github.com/witter-deland/fungible-token-standard/blob/8e5c78ffa58c16207a64e1ad590d9fd309df7630/src/dft_basic/src/canister_api/transfer_notify.rs#L28

> I‘ve find out the reason ((transfer_from.clone(), nat_transfer_value),), should be (transfer_from.clone(), nat_transfer_value,),
> 
> > Thank you very much for your kind reply @domwoe . I'm also wondering why my call to this doesn't work. I believe that the cdk developers have been well tested before release, I am confused, so I came to ask for help, hoping to get help from the cdk developers

**Comment by domwoe** [comment]
@witter-deland It seems that you got it working. Would you mind sharing for others and closing the issue?

Thanks a lot!

**Comment by witter-deland** [comment]
@domwoe No probelm. thanks.
