### ISSUE TITLE
[feature] Provide ic-cdk-optimizer binary as part of releases

### ISSUE THREAD

**Issue by bitdivine** [dfinity/cdk-rs#289]
# Motivation
The `ic-cdk-optimizer` is a bit of a pain to build.  I most often get calls from people where the build fails in one way or another on an M1 mac.  I have tested the build on all the platforms that I have available (Ubuntu x86_64, Intel Mac, M1 Mac) and have in the past got the builds working in all of these cases.  However I'd rather not keep having to go to address build issues.

# Proposed changes
* Build the `ic-cdk-optimizer` for common platforms and provide binaries as part of each release.

Then installation could be just a case of downloading a binary.

I am happy to contribute a PR, but if there is already work on this or if there is a strong reason not to provide binaries, that would be best established before we have spent a lot of time setting up CI.

What do you think?

**Comment by sesi200** [comment]
With dfx 0.11.0, ic-cdk-optimizer is not needed anymore. See https://forum.dfinity.org/t/ledger-wasm-too-big/11274/25 for some more details on this.
