### ISSUE TITLE
`rust-lld: error: duplicate symbol: canister_query http_request` when trying to use `ic-certified-assets`

### ISSUE THREAD

**Issue by paulyoung** [dfinity/cdk-rs#304]
I'm struggling to understand how I might be able to use `ic-certified-assets` to augment some of the methods I already provide in my canister.

I suspect the answer is to split `ic-certified-assets` into two crates; one that providers `lib.rs` and another that provides everything else.

I will try to use Nix's patching feature to remove `lib.rs` locally for now, and add the relevant code from it to my own `lib.rs`

**Comment by smallstepman** [comment]
Checkout GitHub.com/dfinity/certified-assets, it wraps ic-certified-assets to build the WASM.

**Comment by smallstepman** [comment]
Checkout github.com/dfinity/certified-assets where /src/lib.rs wraps ic-certified-assets to build the canister

**Comment by paulyoung** [comment]
Yes, thanks, I've seen that but it doesn't have the same issue I'm facing because the canister doesn't have its own `http_request` method.

**Comment by paulyoung** [comment]
> I suspect the answer is to split `ic-certified-assets` into two crates; one that providers `lib.rs` and another that provides everything else.

Or perhaps just remove the macros so that the methods aren't exported?

Since `ic-certified-assets` uses macros to export canister methods that makes it impossible to use it as a library in a canister that exports the same methods. It seems like dfinity/certified-assets is a more appropriate place to do that.

**Comment by domwoe** [comment]
This relates to #238 as well. It would be great if `ic-certified-assets` would be more modular and extendable.

However, since it now got moved to https://github.com/dfinity/sdk I don't expect that this will happen soon. 
We'd definitely provide support if anyone wants to tackle writing a more modular version or at least would provide input to create a spec for a bounty.

**Comment by paulyoung** [comment]
Back when I was trying this my fork was working well:

https://github.com/dfinity/cdk-rs/compare/main...paulyoung:cdk-rs:paulyoung/ic-certified-assets

I gave up on this approach once I hit the Wasm module function limit though.

Given the trouble I’m having with #310, and that [the Wasm module function limit is going to be increased](https://forum.dfinity.org/t/wasm-module-exceeding-maximum-allowed-functions/12409/36?u=paulyoung), I might need to try this again.

**Comment by smallstepman** [comment]
> Wasm module function limit though
did you strip the binary?
https://github.com/dfinity/sdk/blob/master/scripts/update-frontend-canister.sh#L15-L16

**Comment by smallstepman** [comment]
> Wasm module function limit though
did you strip the binary?
https://github.com/dfinity/sdk/blob/master/scripts/update-frontend-canister.sh#L15-L16

**Comment by paulyoung** [comment]
@smallstepman yes, it’s already optimized using release profile settings and `ic-wasm`

**Comment by paulyoung** [comment]
Closing this since the crate has moved repos. I opened https://github.com/dfinity/sdk/issues/2551 to continue discussing things there.
