### ISSUE TITLE
Rust constraints?

### ISSUE THREAD

**Issue by FrankC01** [dfinity/cdk-rs#319]
Other than wasm (requirement) and IO (constraints) are there any other constraints to be aware of before going full tilt boogies on an application?

TIA

**Comment by adamspofford-dfinity** [comment]
If you already know the effectively-`no_std` implications of wasm32-unknown-unknown, and that most crates offering wasm support are actually offering js-sys support, then the only thing I can think of is that code size is limited to 2MiB (though you can compress with gzip) - assets will need to be uploaded after installation, which we provide as a library [`ic-certified-assets`](https://crates.io/crates/ic-certified-assets).
