### ISSUE TITLE
Can you please support the data structure required to respond to http requests?

### ISSUE THREAD

**Issue by aewc** [dfinity/cdk-rs#328]
Being able to respond to http requests is a major feature of canister.
But there is no standard, optimized, corresponding Struct for `Request/Response` used by canister.

1. [dfn_http/src/types.rs · dfinity/ic](https://github.com/dfinity/ic/blob/81d2e10435/rs/rust_canisters/dfn_http/src/types.rs#L4-L18)(used by Governance, Ledger, CMC, etc.) It doesn't support the update call through http requests.
2. [cycles-wallet/lib.rs · dfinity/cycles-wallet](https://github.com/dfinity/cycles-wallet/blob/fa86dd3a65/wallet/src/lib.rs#L174-L188) (used by cycles-wallet) It doesn't support the update call through http requests.
3. [agent-rs/ic-utils](https://github.com/dfinity/agent-rs/blob/main/ic-utils/src/interfaces/http_request.rs) `ic-utils` is not prepared for canister. In fact, ic-utils needs some system interfaces that cannot be satisfied by wasm, so it cannot be compiled into wasm. In addition to that, its implementation is optimized
4. [cdk-rs](https://github.com/dfinity/cdk-rs/blob/main/src/ic-cdk/src/api/management_canister/http_request.rs#L102-L128) The data structure here is only used for canister to initiate http requests externally, and cannot be used to respond to external http requests

https://github.com/dfinity/agent-rs/issues/201

**Comment by paulyoung** [comment]
I second this.

There are these in `cdk-rs` that I’ve been using most recently:

https://github.com/dfinity/sdk/blob/f4ec163ac968ab94550c01b949a78fd4b8af61ce/src/canisters/frontend/ic-certified-assets/src/types.rs

I was considering creating a similar issue there and/or making a PR to extract them into a separate crate.

**Comment by smallstepman** [comment]
I agree with both of you - I've already been thinking about sth similar and tried doing small refactor in one of my PRs 
https://github.com/dfinity/sdk/blob/a13a2167e4786f82d86ef810575e9ca4f61219a8/src/canisters/frontend/ic-certified-assets/src/state_machine.rs#L906-L1003
 
I want to further discuss the idea of extracting this into a separate crate. Wouldn't something like this satisfy you instead?
```rust
use ic_certified_assets::http::{HttpRequest, HttpResponse}
```
If not, why?

**Comment by aewc** [comment]
Great work.

I found that because of IC limitations, there is not much room for optimization. `HttpRequest` should be the `arg_data()`, which required `ArgumentDecoder` trait, therefore, explicit life cycles are not supported, and Cow, &str, etc. cannot be used.
But `HttpResponse` can using `Cow<'a &str>`
https://github.com/dfinity/examples/blob/master/rust/dip721-nft-container/src/http.rs#L18-L31

**Comment by paulyoung** [comment]
> I want to further discuss the idea of extracting this into a separate crate. Wouldn't something like this satisfy you instead?

@smallstepman I was doing this for a while but then I needed to update some dependency and couldn’t get a version of `candid` that satisfied all the crates involved.

The issues seemed to be be with other parts of the crate so I ended up copying and pasting the `HttpRequest` types I linked above and that let me move on.

**Comment by paulyoung** [comment]
To illustrate this point exactly;

Over 2 months ago https://github.com/dfinity/sdk/pull/2662 upgraded `candid` from `0.7.15` to `0.8.2`, but this version of `ic-certified-assets` hasn’t been published to [crates.io](https://crates.io/crates/ic-certified-assets)

If like me you’re depending on `ic-certified-assets` for the reasons mentioned in this thread and you need to upgrade a dependency which itself upgrades `candid`, you get confusing errors that say something like:

> the trait `CandidType` is not implemented for `<type>`

This is despite `CandidType` clearly being derived and working up until the dependency upgrade.

**Comment by smallstepman** [comment]
hi @paulyoung I can see your point clearly, however, the good news is that we are one step closer to extracting HTTP-related stuff into a separate crate - we recently moved all HTTP-related stuff into a separate file, see https://github.com/dfinity/sdk/blob/master/src/canisters/frontend/ic-certified-assets/src/http.rs. 

In the second half of January I'll extract it properly into a separate crate (that's what I'm aiming at time-wise). 
The reason for this hold-up is the fact there are two additional features that are closely related to canister's HTTP interface (customizable HTTP redirects, and new certification for HTTP requests/responses) - I want these features to get merged before we'll make `ic-http-interface` crate (that way we'll have an easier time drawing the line what goes into the crate and what isn't, and also provide a better level of interface stability from the get-go).

cc @dfx-json

**Comment by paulyoung** [comment]
@smallstepman thanks for the update. 

Since you’ll be working on that soon enough, perhaps it would be worth considering some other feedback I’d seen about the types for handling HTTP requests (what we’re discussing here) being different to the types used for HTTP outcalls.

**Comment by smallstepman** [comment]
I'm not sure that we'll want to merge the types used in those two scenarios (canister's HTTP request endpoint, and HTTP outcalls), as they are not compatible 
- [`HttpRequest` type for HTTP outcalls has fields](https://docs.rs/ic-cdk/latest/ic_cdk/api/management_canister/http_request/struct.CanisterHttpRequestArgument.html) which are not part of the [`HttpRequest` type for the HTTP request endpoint](https://internetcomputer.org/docs/current/references/ic-interface-spec/#http-gateway-interface)
- `HttpResponse` for HTTP request endpoint has to support [`streaming_strategy`](https://internetcomputer.org/docs/current/references/ic-interface-spec/#http-gateway-streaming) and [`upgrade`](https://internetcomputer.org/docs/current/references/ic-interface-spec/#upgrade-to-update-calls) fields and those are missing for [`HttpResponse` type for HTTP Outcalls](https://docs.rs/ic-cdk/latest/ic_cdk/api/management_canister/http_request/struct.HttpResponse.html))

**Comment by paulyoung** [comment]
I think the criticism I’d seen _was_ that they weren’t compatible 🙂

Or, at least, that there’s a subset which is common to both but they’re represented differently.

For example, the [Candid for HttpRequest headers](https://internetcomputer.org/docs/current/references/ic-interface-spec/#http-gateway-interface) is:

```
type HeaderField = record { text; text; };
```

which has been represented in various places in Rust for a while as:

```rust
pub type HeaderField = (String, String);
```

but the more recent HTTP outcalls feature represents [headers](https://docs.rs/ic-cdk/latest/ic_cdk/api/management_canister/http_request/struct.HttpHeader.html) differently:

```rust
pub struct HttpHeader {
    pub name: String,
    pub value: String,
}
```

I’m personally not too affected by this but I wanted to mention it since I’ve seen it brought up a couple of times.

**Comment by smallstepman** [comment]
even `HttpHeader` field in candid is being represented differently for those two features
- https://internetcomputer.org/docs/current/references/ic-interface-spec/#http-gateway-interface
- https://internetcomputer.org/docs/current/references/ic-interface-spec/#ic-candid

Merging everything into shared types would be possible, but at the cost of additional complexity to maintain on our side, instead, it seems we've decided to shift the complexity onto the user, which may not be ideal for beginners but should be beneficial once the end dev gets a hang of it (no extra mental hoops to jump through)
