### ISSUE TITLE
Add 64-bit offset support for std::io traits

### ISSUE THREAD

**Issue by ncpenke** [dfinity/cdk-rs#333]
To make effective use of larger stable storage size, it would be useful to manipulate stable storage via `std::io::Read` and `std::io::Write` traits.

**Comment by ncpenke** [comment]
This [commit](https://github.com/dfinity/cdk-rs/commit/20a65e7b66beb87ed0bbb21d7c9dd8f5c9ef8ca9) fixes this by introducing a new `StableIO` structure that implements both `std::io::Read`, and `std::io::Write`. The existing logic for `StableWriter` and `StableReader` is moved under this structure, and`StableWriter` and `StableReader` are reimplemented as wrappers around `StableIO`.

The motivation for this approach was to allow backwards compatibility with existing API, while layering the new functionality/API on top.

This also fixes https://github.com/dfinity/cdk-rs/issues/334.

If you're interested, I can submit a PR.

**Comment by ncpenke** [comment]
A further iteration on was made by my colleague @dmidem https://github.com/dmidem/cdk-rs/commit/653892c8f5546cbf1bbd4d1c509443bd4df3389a to improve the readability by splitting logic into several files. 

In general happy to make the appropriate cleanup/changes if this is functionality that seems relevant to cdk-rs.

**Comment by lwshang** [comment]
Thanks for the suggestion. Please file a PR.

**Comment by ncpenke** [comment]
Thanks @lwshang created a PR. Happy to incorporate any feedback.
