### ISSUE TITLE
`ic_cdk_timers::TimerId` is not stable memory compatible

### ISSUE THREAD

**Issue by 0kenx** [dfinity/cdk-rs#392]
`ic_cdk_timers::TimerId` is not stable memory compatible, and cannot be converted to `u64` because the methods `as_ffi` and `from_ffi` are not exposed. 

Why is `TimerId` exposed to the public interface at all? Why not expose a u64 instead and convert internally?

**Comment by adamspofford-dfinity** [comment]
`as_ffi` and `from_ffi` are not exposed on TimerId because they are not *on* TimerId; they are on KeyData, which is accessed via `.data()` and `::from`, which *are* exposed.

Furthermore, the entire library is not stable memory compatible - timers will be lost on upgrade - so this is not a concern.
