### ISSUE TITLE
Unsafe unwrap in `ic_cdk_macros::import`

### ISSUE THREAD

**Issue by 0kenx** [dfinity/cdk-rs#394]
https://github.com/dfinity/cdk-rs/blob/1b7cf27ec8c3bc373a025d6201aa069f815a2684/src/ic-cdk-macros/src/import.rs#L96

The expanded code uses `unwrap` for each inter canister call, which is unsafe.

**Comment by chenyan-dfinity** [comment]
This whole module is going to be deprecated in the next CDK release. See https://github.com/dfinity/cdk-rs/pull/390
