### ISSUE TITLE
Dev server

### ISSUE THREAD

**Issue by lastmjs** [dfinity/cdk-rs#402]
The [Motoko Dev Server](https://github.com/dfinity/motoko-dev-server) looks like it will bring a very nice DX to Motoko canister development. What would it take to get this to work for the Rust CDK (and thus also Azle/Kybra)? I'm thinking that the long compile times of Rust will make this very difficult, but technically speaking, are there ways to get around the static Candid serde and the Wasm function exports somehow?

I'm thinking you can't easily get around compiling to Wasm on each deploy.

**Comment by dfx-json** [comment]
Ryan created a repo to experiment with this here: https://github.com/rvanasa/vite-react-ic-rust

The recompilation speed is a bit of an issue. I'm hoping this can inspire a clever innovation. This repo should give us a starting point for how to enable live reload in Azle / Kybra though
