### ISSUE TITLE
Feature: guard function with input parameters

### ISSUE THREAD

**Issue by 0kenx** [dfinity/cdk-rs#414]
It would be useful for the guard function to support input parameters. For example, a guard function can be defined as
```Rust
enum Role {
    Admin,
    User,
}
fn has_role(role: Role) -> Result<(), String>
```
and the corresponding guard would be
`#[update(guard = "has_role(Admin)")]`

**Comment by benjizhai** [comment]
I have implemented this in my Rustic crate's `modifiers` macro https://docs.rs/rustic/0.1.6/rustic/attr.modifiers.html

**Comment by 0kenx** [comment]
Oh that looks nice, thanks!

**Comment by sesi200** [comment]
We're now collecting feature requests over here: https://dx.internetcomputer.org/topic/199
