### ISSUE TITLE
Add `deploy: false` setting to `dfx.json`

### ISSUE THREAD

**Issue by vporton** [dfinity/cdk-rs#417]
Sometimes we need `.did.` (Candid and TypeScript/JavaScript) files for a canister that is not to be deployed by DFX (e.g. it can be deployed by another canister, not by DFX).

If I include it to `dfx.json`, then `dfx` tries to deploy it (what is not what I need).

If I don't include it to `dfx.json`, then I can't generate `.did.` files.

I propose to add some setting like `deploy: false` into the `dfx.json` files to prevent deploying a specific canister, while still compiling it and generating `.did.` files.

**Comment by sesi200** [comment]
Discussed [on the forum](https://forum.dfinity.org/t/how-to-generate-did-files-for-an-actor-class/21468), also not relevant to the CDK
