### ISSUE TITLE
Canister does not rollback when trap occured 

### ISSUE THREAD

**Issue by ljx1990** [dfinity/cdk-rs#425]
ic_cdk:0.10
When i use call_with_payment128 in canister。This problem occurs when http calls or creates canister
The state before call did not rollback when trap occured。
The pseudo code is as follows,Change state from 0 to 1 ：

state = 1
call_with_payment128
panic!

When the trap occurs, the status still changes to 1 and the rollback does not occur.

**Comment by ljx1990** [comment]
Supplement：the common cause of this problem is that cycles is greater than 0 when calling

**Comment by benjizhai** [comment]
This is the intended behaviour of the IC, states do not roll back across async boundaries.

**Comment by adamspofford-dfinity** [comment]
If you would like rollback logic to run when the function is interrupted, you can use `scopeguard`, which provides something akin to `finally`/`defer`.
