### ISSUE TITLE
Why `http_request_required_cycles` is not published?

### ISSUE THREAD

**Issue by linnefromice** [dfinity/cdk-rs#446]
Up to v0.8 the calculation of required_cycles for http_request was included in `http_request`.
However, since then the amount of cycles has been passed as an argument, and the calculation function is not publicly available.
[1] Since there is some fixed method of calculation, can it be published as a default?

Also, the calculation functions in v0.8 and those in v0.11 (in test code) have different digits in their results.
[2] I would like to know the intent of this calculation code.

v0.9 or later (this is v0.11.3)
https://github.com/dfinity/cdk-rs/blob/0b14facb80e161de79264c8f88b1a0c8e18ffcb6/examples/management_canister/src/caller/lib.rs#L7-L19

v0.8
https://github.com/dfinity/cdk-rs/blob/a8454cb37420c200c7b224befd6f68326a01442e/src/ic-cdk/src/api/management_canister/http_request.rs#L290-L299

<details>
<summary>check code</summary>

Cargo.toml
```toml
[dependencies]
candid = "0.9.6"
ic-cdk = "^0.11"
ic-cdk_v08 = { version = "^0.8", package = "ic-cdk" }
```

main.rs
```ts
use ic_cdk::api::management_canister::http_request::CanisterHttpRequestArgument as CanisterHttpRequestArgumentV11;
use ic_cdk_v08::api::management_canister::http_request::CanisterHttpRequestArgument as CanisterHttpRequestArgumentV08;

fn main() {
    println!("Hello, world!");
}

fn http_request_required_cycles_v08(arg: &CanisterHttpRequestArgumentV08) -> u128 {
    let max_response_bytes = match arg.max_response_bytes {
        Some(ref n) => *n as u128,
        None => 2 * 1024 * 1024u128, // default 2MiB
    };
    let arg_raw = ic_cdk_v08::export::candid::utils::encode_args((arg,)).expect("Failed to encode arguments.");
    // The coefficients can be found in [this page](https://internetcomputer.org/docs/current/developer-docs/production/computation-and-storage-costs).
    // 12 is "http_request".len().
    400_000_000u128 + 100_000u128 * (arg_raw.len() as u128 + 12 + max_response_bytes)
}

fn http_request_required_cycles_v11(arg: &CanisterHttpRequestArgumentV11) -> u128 {
    let max_response_bytes = match arg.max_response_bytes {
        Some(ref n) => *n as u128,
        None => 2 * 1024 * 1024u128, // default 2MiB
    };
    let arg_raw = candid::utils::encode_args((arg,)).expect("Failed to encode arguments.");
    // The fee is for a 13-node subnet to demonstrate a typical usage.
    (3_000_000u128
        + 60_000u128 * 13
        + (arg_raw.len() as u128 + "http_request".len() as u128) * 400
        + max_response_bytes * 800)
        * 13
}

#[cfg(test)]
mod tests_v08 {
    use super::*;

    fn arg() -> CanisterHttpRequestArgumentV08 {
        CanisterHttpRequestArgumentV08 {
            url: "https://example.com".to_string(),
            max_response_bytes: Some(3000),
            method: ic_cdk_v08::api::management_canister::http_request::HttpMethod::GET,
            headers: vec![],
            body: None,
            transform: None,
        }
    }

    #[test]
    fn required_cycles_with_some_max() {
        assert_eq!(http_request_required_cycles_v08(&arg()), 718_500_000);
    }

    #[test]
    fn required_cycles_with_none_max() {
        let mut arg = arg();
        arg.max_response_bytes = None;
        assert_eq!(http_request_required_cycles_v08(&arg), 210_132_900_000);
    }
}

#[cfg(test)]
mod tests_v11 {
    use super::*;

    fn arg() -> CanisterHttpRequestArgumentV11 {
        CanisterHttpRequestArgumentV11 {
            url: "https://example.com".to_string(),
            max_response_bytes: Some(3000),
            method: ic_cdk::api::management_canister::http_request::HttpMethod::GET,
            headers: vec![],
            body: None,
            transform: None,
        }
    }

    #[test]
    fn required_cycles_with_some_max() {
        assert_eq!(http_request_required_cycles_v11(&arg()), 81_302_000);
    }

    #[test]
    fn required_cycles_with_none_max() {
        let mut arg = arg();
        arg.max_response_bytes = None;
        assert_eq!(http_request_required_cycles_v11(&arg), 21_860_441_200);
    }
}
```

</details>

**Comment by sesi200** [comment]
I'm not sure about why the formula was changed, but the magic number 12 in v0.8 looks suspiciously like a typo where it should have been a 13. 

It's impossible to calculate the value in general since it depends on the subnet's size. You can find the formula to in the [gas cost table](https://internetcomputer.org/docs/current/developer-docs/gas-cost). Because the canister does not know how many nodes the subnet it is running on contains the canister can't calculate the amount of cycles required.

The assumption that the canister is on a 13 node subnet lead to some annoying problems, so we decided to just remove the method instead

**Comment by linnefromice** [comment]
@sesi200 
This one has not yet been resolved.

By dependent subnet size, you mean the subnet to which the canister making this http_request belongs, correct?
(In that case, it is more difficult for the implementer to calculate.)
Related to your answer, is there an API to get the size of the subnet to which the canister belongs?

>[1] Since there is some fixed method of calculation, can it be published as a default?

Also (even if the size of the subnet cannot be set dynamically), I would like to see the number of subnets as an argument and expose it as a default calculation formula.

**Comment by linnefromice** [comment]
Can you please revert the status of the issue?
I don't have the authority to do this.

**Comment by sesi200** [comment]
I understand this is not resolved, but as of now this will be a WONTFIX for the CDK. It is beyond the scope of just the Rust CDK to provide a future-proof solution. Instead, I created [this feature request](https://dx.internetcomputer.org/topic/203) on our feedback board which we use to prioritise a lot of our work. Feel free to upvote it such that we'll get to it sooner rather than later 🙂

**Comment by linnefromice** [comment]
Thanks for the thoughtful feedback.
I'm going to keep an eye on things there from now on.
