### ISSUE TITLE
Proxy does not work

### ISSUE THREAD

**Issue by vporton** [dfinity/cdk-rs#455]
Try to download https://github.com/vporton/passport-client-dfinity/tree/43b400d2651376cddbc1fdc43d81e0e940016603 and then run

1. `dfx deploy backend`
2. `curl 'http://localhost:3000/api/v2/canister/gf4a7-g4aaa-aaaaa-qaarq-cai/call' -H 'Accept: */*' -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,ru;q=0.7' -H 'Connection: keep-alive' -H 'Content-Type: application/cbor' -H 'Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..sKP0dzSTrnvUjXrg.VMxTpMyD3nLAeZUGjJmpr7IIo7J89EG_YYdM6M7QVr0PazVVvxIBWuefkcMjbQQcbWg0a-adSvgf-SFumUsjIiZu1w9XbTPGSd7FjQJfIWkAExDInPBA3mlTjzdCzeVru37uz-VYFxspkKC9nxzMOyWSspDF_mOKw4teDwEHajuKIiPiDhwjh6xF9UWlk8DhX8h-joylIngq_eQxj71IbGSc_Ya8H2mcg1oeJK81XY6VxLCo6dNjmap8xXCoTIm49iuADl2MS3pY7MItutTF0_LT3wwy90vj2IL5I8K_WRaHfti1NKZ-YTzH5kLz5uJJB4HlFEtOHREP36iCj4iTr97dfP3FqoEyWo7jA34Lt-HC.wtwGsAE0nfnLpXeLP0zQXQ' -H 'Origin: http://localhost:3000' -H 'Referer: http://localhost:3000/' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' -H 'sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120"' -H 'sec-ch-ua-mobile: ?0' -H 'sec-ch-ua-platform: "Linux"' --data-raw $'ÙÙ÷¡gcontent§cargXÆDIDL\u0001l\u0002øÅ®«\u0001q´ã­è\u0009q\u0001\u0000\u0084\u00010x3ee0dc43440e1132aa506de9dfa547ab0f69fc2a6d22d535a1bae3502699f28257410511f4830aec198df2676480ed18e0e1b8d9c5a18a4e5e4c0534c0cabfe91b*0xF321940F3D1599a1336CA33f08015dB52eDB0A14kcanister_idJ\u0080\u0000\u0000\u0000\u0000\u0010\u0000#\u0001\u0001ningress_expiry\u001b\u0017ª¾*Ïõ\u0008\u0000kmethod_namex\u001cscoreBySignedEthereumAddressenoncePXa±õ&\u0015Ts\u0096|>\u0011²¶ïxlrequest_typedcallfsenderA\u0004'`

The second command is copied from the browser “Export to cURL”.

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /api/v2/canister/gf4a7-g4aaa-aaaaa-qaarq-cai/call</pre>
</body>
</html>
```
```plain
$ dfx --version
dfx 0.15.2+rev15.283413df
```

Queries through http://127.0.0.1:4943/?canisterId=bw4dl-smaaa-aaaaa-qaacq-cai&id=bkyz2-fmaaa-aaaaa-qaaaq-cai do work.

But in the browser
```
Cannot POST /api/v2/canister/bkyz2-fmaaa-aaaaa-qaaaq-cai/call
```

So, (both in the browser, the first is through using http://127.0.0.1:4943/?canisterId=bw4dl-smaaa-aaaaa-qaacq-cai&id=bkyz2-fmaaa-aaaaa-qaaaq-cai)
```
POST http://127.0.0.1:4943/api/v2/canister/bkyz2-fmaaa-aaaaa-qaaaq-cai/call
```
works and
```
POST http://localhost:3000/api/v2/canister/bkyz2-fmaaa-aaaaa-qaaaq-cai/call
```
doesn’t.

More information about this bug at https://forum.dfinity.org/t/troubleshooting-agenthttpresponseerror/23846

**Comment by vporton** [comment]
Even worse:

Directly after
```$ dfx deploy
...
    backend: http://127.0.0.1:4943/?canisterId=be2us-64aaa-aaaaa-qaabq-cai&id=bkyz2-fmaaa-aaaaa-qaaaq-cai
...
```

When I try to open http://127.0.0.1:4943/?canisterId=be2us-64aaa-aaaaa-qaabq-cai&id=bkyz2-fmaaa-aaaaa-qaaaq-cai I get:
```
Could not find a canister id to forward to.
```

**Comment by vporton** [comment]
Removing `~/.dfinity` did solve `Could not find a canister id to forward to.` but not the proxy 404 bug.

**Comment by krpeacock** [comment]
interesting - the localhost known host bug should have been fixed in [0.20.2](https://github.com/dfinity/agent-js/releases/tag/v0.20.2). I'll have to figure out what's going on

**Comment by vporton** [comment]
I realized that the above are usual response of a `react-scripts` app running on port 3000.

My app does not know about Replica running locally.

Now I wonder, why something similar wonder in the past.

@krpeacock How to run `npm start` in such a way that `new HttpAgent` would connect to correct port, not to the same 3000 port that is used by `npm start`?

**Comment by vporton** [comment]
> why something similar wonder in the past

Should read "why something similar worked in the past".

**Comment by vporton** [comment]
Apparently, if we use identity got from `client.getIdentity()` from `await AuthClient.create(props.options!.createOptions)` to initialize `HttpAgent` (`new HttpAgent({identity})`), then it works (when frontend run from `npm start`), otherwise, it doesn't.

Still need to investigate.
