### ISSUE TITLE
Feature: Download canister .did and .most

### ISSUE THREAD

**Issue by vporton** [dfinity/cdk-rs#477]
Please add a command to download canister's `.did` and `.most`.

Currently I do [my code](https://github.com/vporton/NacDB/blob/make-rules/Makefile) hacky:

```make
%.install: %.wasm FORCE
	dfx canister create $(*F)
	dfx canister install --network=$(NETWORK) -m install --wasm=$< $(*F)

%.upgrade: %.wasm %.most FORCE
	mkdir -p $(DFXDIR)/.dfx/local/canisters/$(*F)
	cp -f $*.most $(DFXDIR)/.dfx/local/canisters/$(*F)/ # hack!
	cp -f $*.did $(DFXDIR)/.dfx/local/canisters/$(*F)/constructor.did # hack!
	dfx canister install --network=$(NETWORK) -m upgrade --wasm=$< $(*F)
```

I want to use `moc --stable-compatible` explicitly to avoid hacks, what is possible only when I get direct access to such canister data.

**Comment by chenyan-dfinity** [comment]
To get it from deployed canisters: `dfx canister metadata <canister_id> motoko:stable-types`.
To get it from wasm: `ic-wasm <my.wasm> metadata motoko:stable-types`.

If you want to make it everything explicit and scriptable, I encourage you to try `ic-repl`.

**Comment by vporton** [comment]
OK, `dfx canister metadata <canister_id> motoko:stable-types` gives `.did`. But how to get `.most`? (And I don't really understand what is the distinction between `.did` and `.most`.)

Also, the following demonstrates that `stresser` does have `main` shared method, but it is missing in the `actor`:

```
$ dfx canister metadata stresser motoko:stable-types && dfx canister call stresser main '()'
// Version: 1.0.0
actor {
  
};
Error: Failed update call.
Caused by: Failed update call.
  The replica returned a replica error: reject code CanisterReject, reject message IC0501: Canister bkyz2-fmaaa-aaaaa-qaaaq-cai is out of cycles, error code None
```

```
$ dfx --version
dfx 0.18.0
```

**Comment by chenyan-dfinity** [comment]
`motoko:stable-types` gives you `.most`. `candid:service` gives you `.did`

**Comment by lwshang** [comment]
This doesn't seem to be an issue with Rust CDK but rather with general development using dfx.
