### ISSUE TITLE
Issue using `candid-derive` with wasm binary assets in canister

### ISSUE THREAD

**Issue by muse254** [dfinity/cdk-rs#501]
I have canister code that loads a static binary asset as `&[u8]` at compile-time. When trying to generate the .did file I run into an issue about not finding an import. For my case the canister is meant partly as an asset store
```
Error: unknown import: `wapc::__guest_request` has not been defined
```

**Comment by chenyan-dfinity** [comment]
It seems one of your library imports the `wapc` module, which is not allowed by the IC. It's not a Candid export problem. If we try to deploy the Wasm to IC without Candid, you will probably get the same error.

**Comment by muse254** [comment]
That fixed the issue. Thank you @chenyan-dfinity
