### ISSUE TITLE
Tutorials: Rust basic dependency tutorial

### ISSUE THREAD

**Issue by Qweder93** [dfinity/cdk-rs#51]
Hello, I tried to reproduce examples from your guide for rust: https://sdk.dfinity.org/docs/rust-guide/multiply-dependency.html. 
First of all this link isn't working https://sdk.dfinity.org/quickstart/quickstart.html#download-and-install
Then I made all steps that were in the instruction, changing paths to my local and after I successfully started the Internet Computer network and called in second terminal "dfx deploy" I received such an error :
'cargo build --target wasm32-unknown-unknown --package  rust_deps --release'
thread 'main' panicked at 'Could not run custom tool.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/dfx/src/lib/builders/custom.rs:181:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Could you please help me to understand what could I do wrong? 
Examples with Motoko worked perfect for me, but in case with rust it can't find some directories.
upd. Same error for other examples

**Comment by lsgunnlsgunn** [comment]
Thanks for trying this out and letting us know about the problems you ran into. There have been a lot of changes under the hood and now the tutorials for Rust need to be refreshed. We'll try to get updated docs out soon!

**Comment by lsgunnlsgunn** [comment]
@ililic , any chance you can take a look at this to see if we can track down how to fix the Rust tutorials?

**Comment by umeklinks** [comment]
I get similar error:

`The post-build step failed for canister 'rrkah-fqaaa-aaaaa-aaaaq-cai' with an embedded error: No such file or directory (os error 2)`

and I can't figure out where the issue is from.

**Comment by ggreif** [comment]
`$ ls .dfx/local/canisters/idl/`: directory exists, but is empty.

=> so `canister.rs:282` must  be failing

**Comment by koakh** [comment]
hello

I'm following the tutorial 
https://sdk.dfinity.org/docs/rust-guide/rust-quickstart.html
and have problems to I fixed with this steps

```shell
$ rustup install nightly-x86_64-unknown-linux-gnu
$ rustup target add wasm32-unknown-unknown --toolchain nightly
$ rustup run nightly cargo build --target wasm32-unknown-unknown
$ rustup target add wasm32-unknown-unknown
$ dfx deploy
```

but now I landed in same error that was mentioned by @ggreif 

```shell
$ dfx deploy
The post-build step failed for canister 'rrkah-fqaaa-aaaaa-aaaaq-cai' with an embedded error: No such file or directory (os error 2)
mario@koakh-laptop:~/Development/DFinity/rust_hello> ls .dfx/local/canisters/idl/
ls: cannot access '.dfx/local/canisters/idl/': No such file or directory
mario@koakh-laptop:~/Development/DFinity/rust_hello> Jun 06 21:44:51.887 WARN s:/n:/ic_crypto_internal_csp/proto_store WARNING: deleting key with ID KeyId(0x8bdba52ef24fe4216783e17e8d5f6542e22e5d3a734086edce80c4b5701fee59) with scope Const:NiDkgThresholdKeys
Jun 06 21:49:11.891 WARN s:/n:/ic_crypto_internal_csp/proto_store WARNING: deleting key with ID KeyId(0xc987f77814fc8881bf80592f074929172191dc512d30028295d656e8a8e4fae2) with scope Const:NiDkgThresholdKeys
```

any help to solve this problem of `'.dfx/local/canisters/idl/': No such file or directory`

thanks

**Comment by paulyoung** [comment]
Possibly the same issue I reported in #100 with a similar fix to the one I made in #101.

**Comment by koakh** [comment]
thanks @paulyoung It is working the problem is a wrong file location in file `src/rust_hello/rust_hello.did`
tutorial says 

OK Create a new file in the `src/rust_hello/` directory named rust_hello.did.
KO Open the `src/rust_hello/src/rust_hello.did` file in a text editor.

but it is 
OK Create a new file in the `src/rust_hello/` directory named 
OK Open the `src/rust_hello/rust_hello.did` file in a text editor.

**Comment by Bill0412** [comment]
I had a similar issue when trying https://smartcontracts.org/docs/rust-guide/multiply-dependency.html, and was solved by putting the `.did` file in the location as specified in my `dfx.json`.

**Comment by paulyoung** [comment]
> `The post-build step failed for canister 'rrkah-fqaaa-aaaaa-aaaaq-cai' with an embedded error: No such file or directory (os error 2)`

This error also occurs if the package name contains a hyphen, e.g. `foo-bar`, because the generated Wasm file ends up at `target/wasm32-unknown-unknown/release/foo_bar.wasm`
