### ISSUE TITLE
Get return values from `ic_cdk::block_on`

### ISSUE THREAD

**Issue by sasa-tomic** [dfinity/cdk-rs#7]
To make Rust-CDK `block_on` implementation compatible with the regular Rust `block_on` implementation it would be great if we could return values in our implementation of this function.

Rust CDK block_on implementation https://github.com/dfinity/rust-cdk/blob/01221cfd38df9ea85aa85fd7af56a0e87f3e8f6f/src/ic_cdk/src/lib.rs#L27
```
pub fn block_on<F: 'static + std::future::Future<Output = ()>>(future: F) -> ();
```

Rust Futures block_on implementation https://docs.rs/futures/0.3.5/futures/executor/fn.block_on.html
```
pub fn block_on<F: Future>(f: F) -> F::Output;
```

This is needed in my case to enable native execution testing for the canister code, but I believe it would also be useful for other users of the Rust CDK.

**Comment by lastmjs** [comment]
Hey, I would love to see this! Would you accept a pull request?

**Comment by lwshang** [comment]
Thanks for the advice, we SDK team is working on it

**Comment by lastmjs** [comment]
Do you have an ETA? Days, weeks, months? Just wondering if I should implement it myself in the mean time, since I could really use this functionality

**Comment by lastmjs** [comment]
`block_on` doesn't really block it seems. I see there's a pull request to rename `block_on` to spawn, which does make more sense. But it would be really useful to have a `block_on` still that actually blocks (at least syntactically) and returns the future output.

**Comment by roman-kashitsyn** [comment]
I don't think returning a value is possible.
The name `block_on` was is a misnomer: this function doesn't block!
I have a PR in flight to fix that: https://github.com/dfinity/cdk-rs/pull/110
And then I found that Hans created a similar PR 8 months ago https://github.com/dfinity/cdk-rs/pull/75

**Comment by sasa-tomic** [comment]
Thanks @roman-kashitsyn ! Let me know if you need an approval for #110. It's sad that we still don't have the basic `block_on`. But getting the naming right is a first good step. :)

**Comment by sasa-tomic** [comment]
@lastmjs I'll make sure your PR gets an appropriate attention. Feel free to send it this way.

**Comment by lastmjs** [comment]
Here's a minimal working (not working) example of what needs to be done to solve my issue (and hopefully others' as well): https://github.com/lastmjs/test-ic-boa-async
