### ISSUE TITLE
API function for canister creation

### ISSUE THREAD

**Issue by sasa-tomic** [dfinity/cdk-rs#9]
Can we please get a function in the Rust CDK for canister creation and installation.
https://docs.dfinity.systems/public/#ic-create_canister

The replica used in DFX already supports this functionality, we only need some interface functions

**Comment by flyq** [comment]
> > Replica-internals, as in stuff not documentd in the Public Spec? What would they be?
> 
> As in: it's _mandatory_ to provide a struct called exactly `InstallCodeArgs` with fields called exactly this and that. Changes in the fields of this struct become increasingly difficult if canisters depend directly on them.
> 
> Similar thing for https://github.com/dfinity/bigmap-rs/blob/9ade1529d6a1816ae56c52c9167c520f72f303f8/src/canister_management.rs#L5 (`CanisterIdRecord`). Canister creation doesn't work if the struct is named something else.

The github link is broken

**Comment by hansl** [comment]
> The github link is broken

It's not, bigmap-rs is currently private.  For reference, the structure referred to looks like this:

```rust
#[derive(CandidType, serde::Deserialize, Debug)]
struct CanisterIdRecord {
    canister_id: candid::Principal,
}
```
